"""date field in Compra model changed to buy_date

Revision ID: d54676dc0861
Revises: 9c34f4235482
Create Date: 2022-12-28 12:36:39.751784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d54676dc0861"
down_revision = "9c34f4235482"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_compra", sa.Column("buy_date", sa.Date(), nullable=True))
    op.drop_column("tb_compra", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tb_compra", sa.Column("date", sa.DATE(), autoincrement=False, nullable=True)
    )
    op.drop_column("tb_compra", "buy_date")
    # ### end Alembic commands ###
